Issue 69 requirements
TIS2017/Nobelisti pull request #72
Opened 2018-01-01 18:47 UTC by ZoltanOnody

closes #69 

- pridal som requirements do route
- zjednotil som pouzite `methods="..."` a `@Method`
- prepisanie 2 routy sposobilo redundantny kod tak som ho zmazal

vsetko som preklikat a vyzera to tak, ze to funguje :)

2018-01-01 18:49 UTC, ZoltanOnody commented on src/src/AdminBundle/Controller/EventController.php
> -        $eventType = $repository->findOneBy(['id' => intval($id)]);
@nitrajka, zmazal som `intval` kedze to funguje aj bez toho a nikde to nepouzivame, bol tam nejaky specialny dovod preco si ho pridala?

2018-01-07 14:24 UTC, Radcho requested changes
Neviem to normalne linknut, ale na https://github.com/TIS2017/Nobelisti/blob/aaf5a4c288fd6e97969f3d2c6b4350254a5cc094/src/src/AdminBundle/Controller/OrganizerController.php#L79 chyba id requirement.

2018-01-07 16:53 UTC, ZoltanOnody commented
Vdaka, pridal som

2018-01-07 20:35 UTC, Radcho approved these changes

2018-01-07 21:32 UTC, merged